import numpy as np
ogarray = np.linspace(0, 9, 10, dtype=int)
print("original array:")
print(ogarray)
new = np.where(ogarray % 2 != 0, -1, ogarray)
print("\nmodified array (odd numbers replaced with -1):")
print(new)
two_d_array = ogarray.reshape(2, -1)
print("\n2D array (2 rows):")
print(two_d_array)
sum_all = np.sum(ogarray)
print("\nsum of all numbers in original array:")
print(sum_all)